$rosewater = rgb(c35e0a)
$rosewaterAlpha = c35e0a

$flamingo = rgb(d65d0e)
$flamingoAlpha = d65d0e

$pink = rgb(b16286)
$pinkAlpha = b16286

$mauve = rgb(8f3f71)
$mauveAlpha = 8f3f71

$red = rgb(9d0006)
$redAlpha = 9d0006

$maroon = rgb(af3a03)
$maroonAlpha = af3a03

$peach = rgb(d65d0e)
$peachAlpha = d65d0e

$yellow = rgb(b57614)
$yellowAlpha = b57614

$green = rgb(79740e)
$greenAlpha = 79740e

$teal = rgb(427b58)
$tealAlpha = 427b58

$sky = rgb(689d6a)
$skyAlpha = 689d6a

$sapphire = rgb(458588)
$sapphireAlpha = 458588

$blue = rgb(076678)
$blueAlpha = 076678

$lavender = rgb(8f3f71)
$lavenderAlpha = 8f3f71

$text = rgb(3c3836)
$textAlpha = 3c3836

$subtext1 = rgb(504945)
$subtext1Alpha = 504945

$subtext0 = rgb(665c54)
$subtext0Alpha = 665c54

$overlay2 = rgb(7c6f64)
$overlay2Alpha = 7c6f64

$overlay1 = rgb(928374)
$overlay1Alpha = 928374

$overlay0 = rgb(a89984)
$overlay0Alpha = a89984

$surface2 = rgb(bdae93)
$surface2Alpha = bdae93

$surface1 = rgb(d5c4a1)
$surface1Alpha = d5c4a1

$surface0 = rgb(ebdbb2)
$surface0Alpha = ebdbb2

$base = rgb(f2e5bc)
$baseAlpha = f2e5bc

$mantle = rgb(ebdbb2)
$mantleAlpha = ebdbb2

$crust = rgb(d5c4a1)
$crustAlpha = d5c4a1
