foreground            #291714
background            #fff8f7
selection_foreground  #ffffff
selection_background  #bc0004
url_color             #006097
cursor                #bc0004
cursor_text_color     #ffffff

color0   #fff8f7
color1   #ba1a1a
color2   #bc0004
color3   #006097
color4   #bc0004
color5   #006097
color6   #007abd
color7   #291714

color8   #936e69
color9   #ba1a1a
color10  #bc0004
color11  #006097
color12  #bc0004
color13  #006097
color14  #007abd
color15  #291714

tab_bar_background              #fff8f7
tab_bar_margin_color            #fff8f7
active_tab_foreground           #ffffff
active_tab_background           #bc0004
inactive_tab_foreground         #5e3f3a
inactive_tab_background         #fff8f7
